package Tela;

import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
import javax.swing.*;
import notacao.Expressao;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author u10265
 */
public class Tela extends javax.swing.JFrame {
      private String valor;    //meu Valor TRabalha como IR   
     
   
 

         public Tela(String S) {
                
                // super chama o constructor da classe JFrame
                super();
                            
// Opcodes das Operacoes tem limpa e trazer resultado da operacao
                /*Opcode das instruções:
		
		+: soma conteudo
		-: subtrai conteudo
		\: divide conteudo
		=: Traz conteudo da MBR da saida pronto 
                   e imprime todo o conteúdo da memória de dados!!!!
		C: cleaner limpa 
	          */

                soma = new JButton("+");
                subtrai = new JButton("-");
                multip = new JButton("x");
                divide = new JButton("/");
                
              
                //ntrada = new JTextField("");
         }
          public String getValorEntrada(){
                    return this.entrada.getText();
                }        
                // botões ganha uma  ActionListener(para ações)
             
      /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        valor="";
 
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jXImagePanel1 = new org.jdesktop.swingx.JXImagePanel();
        jPanel2 = new javax.swing.JPanel();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        entrada = new javax.swing.JTextField();
        numero3 = new javax.swing.JButton();
        numero2 = new javax.swing.JButton();
        numero1 = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        multip = new javax.swing.JButton();
        numero4 = new javax.swing.JButton();
        numero5 = new javax.swing.JButton();
        numero6 = new javax.swing.JButton();
        numero8 = new javax.swing.JButton();
        numero9 = new javax.swing.JButton();
        numero0 = new javax.swing.JButton();
        soma = new javax.swing.JButton();
        limpa = new javax.swing.JButton();
        subtrai = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        posfixa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        VetorCampo = new javax.swing.JTextField();
        vetor = new javax.swing.JLabel();
        sete = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jXImagePanel1Layout = new javax.swing.GroupLayout(jXImagePanel1);
        jXImagePanel1.setLayout(jXImagePanel1Layout);
        jXImagePanel1Layout.setHorizontalGroup(
            jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jXImagePanel1Layout.setVerticalGroup(
            jXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, new java.awt.Color(51, 0, 255), java.awt.Color.black, java.awt.Color.blue));
        jPanel2.setToolTipText("");

        uJPanelImagem1.setImagem(new java.io.File("C:\\Users\\Ernani Batista\\Desktop\\estruturas\\ErnaniCalculadora\\Notacao\\src\\fundo.jpg"));

        entrada.setEditable(false);
        entrada.setBackground(new java.awt.Color(255, 255, 204));
        entrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        entrada.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 204)));
        entrada.setDisabledTextColor(new java.awt.Color(51, 0, 204));
        entrada.setName("resultado"); // NOI18N

        numero3.setText("3");
        numero3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numero3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero3MouseClicked(evt);
            }
        });

        numero2.setText("2");
        numero2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero2MouseClicked(evt);
            }
        });

        numero1.setBackground(new java.awt.Color(204, 204, 204));
        numero1.setText("1");
        numero1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero1MouseClicked(evt);
            }
        });
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });

        divide.setToolTipText("");
        divide.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        divide.setLabel("/");
        divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divideMouseClicked(evt);
            }
        });
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        multip.setText("*");
        multip.setToolTipText("");
        multip.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        multip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multipMouseClicked(evt);
            }
        });
        multip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipActionPerformed(evt);
            }
        });

        numero4.setText("4");
        numero4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numero4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero4MouseClicked(evt);
            }
        });

        numero5.setText("5");
        numero5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numero5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero5MouseClicked(evt);
            }
        });

        numero6.setText("6");
        numero6.setToolTipText("");
        numero6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numero6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero6MouseClicked(evt);
            }
        });

        numero8.setText("8");
        numero8.setToolTipText("");
        numero8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numero8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero8MouseClicked(evt);
            }
        });

        numero9.setText("9");
        numero9.setToolTipText("");
        numero9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numero9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero9MouseClicked(evt);
            }
        });

        numero0.setText("0");
        numero0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numero0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero0MouseClicked(evt);
            }
        });

        soma.setToolTipText("");
        soma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        soma.setLabel("+");
        soma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                somaMouseClicked(evt);
            }
        });

        limpa.setText("CE");
        limpa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        limpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpaMouseClicked(evt);
            }
        });
        limpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaActionPerformed(evt);
            }
        });

        subtrai.setText("-");
        subtrai.setToolTipText("");
        subtrai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        subtrai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtraiMouseClicked(evt);
            }
        });

        igual.setText("=");
        igual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        igual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                igualKeyPressed(evt);
            }
        });

        posfixa.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Expressão PosFixa");
        jLabel1.setToolTipText("");

        VetorCampo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        vetor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vetor.setForeground(new java.awt.Color(255, 255, 0));
        vetor.setText("Vetor Ficou");

        sete.setText("7");
        sete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(numero4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numero1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(sete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numero2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                    .addComponent(numero5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numero6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                    .addComponent(numero3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                .addComponent(numero8, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numero0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                .addComponent(limpa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                    .addComponent(multip, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, uJPanelImagem1Layout.createSequentialGroup()
                                    .addComponent(soma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(subtrai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posfixa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(VetorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vetor)
                                .addGap(8, 8, 8)))))
                .addGap(32, 32, 32))
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multip, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soma, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtrai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limpa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem1Layout.createSequentialGroup()
                                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numero0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vetor, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posfixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VetorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        numero3.getAccessibleContext().setAccessibleName("numero3");
        numero2.getAccessibleContext().setAccessibleName("numero2");
        numero1.getAccessibleContext().setAccessibleName("numero1");
        divide.getAccessibleContext().setAccessibleName("dividir");
        multip.getAccessibleContext().setAccessibleName("vezes");
        numero4.getAccessibleContext().setAccessibleName("numero4");
        numero5.getAccessibleContext().setAccessibleName("numero5");
        numero6.getAccessibleContext().setAccessibleName("numero6");
        numero8.getAccessibleContext().setAccessibleName("numero8");
        numero9.getAccessibleContext().setAccessibleName("numero9");
        numero0.getAccessibleContext().setAccessibleName("numero0");
        soma.getAccessibleContext().setAccessibleName("soma");
        subtrai.getAccessibleContext().setAccessibleName("sub");
        igual.getAccessibleContext().setAccessibleName("igualdade");
        igual.getAccessibleContext().setAccessibleDescription("");
        posfixa.getAccessibleContext().setAccessibleName("posFixa");
        VetorCampo.getAccessibleContext().setAccessibleName("vetorCampo");
        vetor.getAccessibleContext().setAccessibleName("vector");
        sete.getAccessibleContext().setAccessibleName("sete");
        sete.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void igualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_igualKeyPressed
        // TODO add your handling code here:

        igual.registerKeyboardAction(igual.getActionForKeyStroke(
                KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, false)),
                KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
                JComponent.WHEN_FOCUSED);

        // int tecla = evt.getKeyCode();  

        // if ( tecla == KeyEvent.VK_ENTER  && ( ( JButton) evt.getSource() ).hasFocus() ) {
        //  igual.doClick();
        //}



    }//GEN-LAST:event_igualKeyPressed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        // TODO add your handling code here:
        String expressao = entrada.getText();
        //pega entrada de strings da tela
        // passa ser numero da memoria
        Expressao ex = new Expressao(expressao.length());
         //instancia uma niva expressao a ser empilhada
        // enfineilarada de acordo com  procedencia
        
        //srintg tokenizer que quebra a expressao de acordo com simbolo de operacao
        StringTokenizer quebrador = new StringTokenizer(expressao, "+-*/^()", true);

        // enquanto houver Tolkens ou seja operacoes 
        //vai implementando as operacoes
        while (quebrador.hasMoreTokens()) {
            ex.implementaExpressao(quebrador.nextToken());
        }
        
        VetorCampo.setText(ex + "");
        //System.out.println(ex);
        ex.RetornaVetorString(entrada.getText());

        try {
            posfixa.setText(ex.transformaPosFixa());
            
            // ou seja  escreve os elementos da operacao
            // em ordem de procedencia exemplo () primeiro
            // multiplicacao soma depois
            
            //System.out.println();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            entrada.setText(ex.retornaResultado() + "");
            
            // System.out.println("Resultado da Expressao"+" "+ex.retornaResultado());
        } catch (Exception a) {
        }
    }//GEN-LAST:event_igualActionPerformed

    private void subtraiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtraiMouseClicked
        // TODO add your handling code here:
        valor += "-";
        entrada.setText(valor);
    }//GEN-LAST:event_subtraiMouseClicked

    private void limpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpaMouseClicked
        // TODO add your handling code here:
        valor = "";
        entrada.setText("");
    }//GEN-LAST:event_limpaMouseClicked

    private void somaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_somaMouseClicked
        // TODO add your handling code here:
        valor += "+";
        entrada.setText(valor);
    }//GEN-LAST:event_somaMouseClicked

    private void numero0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero0MouseClicked
        // TODO add your handling code here:
        valor += "0";
        entrada.setText(valor);
    }//GEN-LAST:event_numero0MouseClicked

    private void numero9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero9MouseClicked
        // TODO add your handling code here:
        valor += "9";
        entrada.setText(valor);
    }//GEN-LAST:event_numero9MouseClicked

    private void numero8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero8MouseClicked
        // TODO add your handling code here:
        valor += "8";
        entrada.setText(valor);
    }//GEN-LAST:event_numero8MouseClicked

    private void numero6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero6MouseClicked
        // TODO add your handling code here:
        valor += "6";
        entrada.setText(valor);
    }//GEN-LAST:event_numero6MouseClicked

    private void numero5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero5MouseClicked
        // TODO add your handling code here:
        valor += "5";
        entrada.setText(valor);
    }//GEN-LAST:event_numero5MouseClicked

    private void numero4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero4MouseClicked
        // TODO add your handling code here:
        valor += "4";
        entrada.setText(valor);
    }//GEN-LAST:event_numero4MouseClicked

    private void multipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multipMouseClicked
        // TODO add your handling code here:
        valor += "*";
        entrada.setText(valor);
    }//GEN-LAST:event_multipMouseClicked

    private void divideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divideMouseClicked
        // TODO add your handling code here:
        valor += "/";
        entrada.setText(valor);
    }//GEN-LAST:event_divideMouseClicked

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        // TODO add your handling code here:

  }//GEN-LAST:event_numero1ActionPerformed

    private void numero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero1MouseClicked
        // TODO add your handling code here:
        valor += "1";
        entrada.setText(valor);
    }//GEN-LAST:event_numero1MouseClicked

    private void numero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero2MouseClicked
        // TODO add your handling code here:
        valor += "2";
        entrada.setText(valor);
    }//GEN-LAST:event_numero2MouseClicked

    private void numero3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero3MouseClicked
        // TODO add your handling code here:
        valor += "3";
        entrada.setText(valor);
    }//GEN-LAST:event_numero3MouseClicked

    private void seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteActionPerformed
        // TODO add your handling code here:
        valor += "7";
        entrada.setText(valor);
    }//GEN-LAST:event_seteActionPerformed
    private void limpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpaActionPerformed

    private void multipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multipActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divideActionPerformed
  
    
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, NumberFormatException, Exception {
        

         
          
        
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Tela().setVisible(true);
            }
        });
        
  
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VetorCampo;
    private javax.swing.JButton divide;
    private javax.swing.JTextField entrada;
    private javax.swing.JButton igual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jdesktop.swingx.JXImagePanel jXImagePanel1;
    private javax.swing.JButton limpa;
    private javax.swing.JButton multip;
    private javax.swing.JButton numero0;
    private javax.swing.JButton numero1;
    private javax.swing.JButton numero2;
    private javax.swing.JButton numero3;
    private javax.swing.JButton numero4;
    private javax.swing.JButton numero5;
    private javax.swing.JButton numero6;
    private javax.swing.JButton numero8;
    private javax.swing.JButton numero9;
    private javax.swing.JTextField posfixa;
    private javax.swing.JButton sete;
    private javax.swing.JButton soma;
    private javax.swing.JButton subtrai;
    private componentes.UJPanelImagem uJPanelImagem1;
    private javax.swing.JLabel vetor;
    // End of variables declaration//GEN-END:variables
}
